<?php

namespace MitaJunior\Workflow\Models;

use Illuminate\Database\Eloquent\Model;

class Stage extends Model {

    protected $table = 'm_stages';

    protected $guarded = [];

    public function workflow()
    {
        return $this->belongsTo(Workflow::class, 'workflow_id');
    }

    public function actions()
    {
        return $this->hasMany(Action::class, 'stage_id');
    }

    public function expired_stage()
    {
        return $this->belongsTo(self::class, 'expired_stage_id');
    }

    public function __toString()
    {
        return $this->name; // TODO: Change the autogenerated stub
    }
}